packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - "@swc/core"
  - "es5-ext"
  - "prisma"
  - "sharp"
  - "unrs-resolver"
