import type { Locale } from './config'

type Messages = Record<string, string>

const en: Messages = {
  language: 'Language', search: 'Search plugins, scripts, tutorials...', upload: 'Upload product', sellerApply: 'Become a seller',
  productsManage: 'Manage products', settings: 'Settings', logout: 'Sign out', cart: 'Cart', login: 'Sign in',
  all: 'All', free: 'Free', bestSelling: 'Best selling', featured: 'Featured', latest: 'Latest', popular: 'Most popular',
  topRated: 'Top rated', priceLow: 'Price: low to high', priceHigh: 'Price: high to low', sort: 'Sort by:', categories: 'Categories',
  home: 'Home', searchShort: 'Search', wishlist: 'Wishlist', notifications: 'Notifications', help: 'Help', new: 'NEW',
  trending: 'Trending', recentlyViewed: 'Recently viewed', clear: 'Clear', products: '{count} products', productsFor: '{count} products for "{query}"',
  noResultsFor: 'No results for "{query}"', noFavorites: 'No favorite products yet', favoriteHint: 'Tap the heart on a product to save it',
  noResults: 'No results found', searchHint: 'Try another keyword or browse a category', noProducts: 'No products yet',
  sales: '{count} sold', views: '{count} views', description: 'Description', price: 'Price', downloadFree: 'Download free',
  favorite: 'Favorite', liked: 'Liked', copyLink: 'Copy link', copied: 'Copied', report: 'Report', addToCart: 'Add to cart', buyNow: 'Buy now', downloading: 'Downloading...', comingSoon: 'Coming soon',
  cartEmpty: 'Your cart is empty', continueShopping: 'Continue shopping', total: 'Total', getFree: 'Get free products',
  paymentLocked: 'Payments temporarily unavailable', clearAll: 'Clear all', marketplaceAbout: 'The marketplace for REAPER plugins, scripts and extensions. High quality, fair prices.',
  marketplace: 'Marketplace', allProducts: 'All products', support: 'Support', installGuide: 'Installation guide', contact: 'Contact',
  refundPolicy: 'Refund policy', forSellers: 'For sellers', sellProduct: 'Sell a product', developerGuide: 'Developer guide', rights: 'All rights reserved.',
  forReaper: 'for REAPER', removeFromWishlist: 'Remove {title} from wishlist', addToWishlist: 'Add {title} to wishlist', ratingOutOfFive: '{rating} out of 5 stars', productTags: 'Product tags', downloadPurchased: 'Download (Purchased)',
  sellerDashboard: 'Seller Dashboard', apiDocs: 'API Documentation',
}

const vi: Messages = {
  language: 'Ngôn ngữ', search: 'Tìm plugin, script, tutorial...', upload: 'Đăng sản phẩm', sellerApply: 'Đăng ký Seller',
  productsManage: 'Quản lý sản phẩm', settings: 'Cài đặt', logout: 'Đăng xuất', cart: 'Giỏ hàng', login: 'Đăng nhập',
  all: 'Tất cả', free: 'Miễn phí', bestSelling: 'Bán chạy', featured: 'Nổi bật', latest: 'Mới nhất', popular: 'Phổ biến nhất',
  topRated: 'Đánh giá cao', priceLow: 'Giá thấp → cao', priceHigh: 'Giá cao → thấp', sort: 'Sắp xếp:', categories: 'Danh mục',
  home: 'Trang chủ', searchShort: 'Tìm kiếm', wishlist: 'Yêu thích', notifications: 'Thông báo', help: 'Trợ giúp', new: 'MỚI',
  trending: 'Đang thịnh hành', recentlyViewed: 'Xem gần đây', clear: 'Xóa', products: '{count} sản phẩm', productsFor: '{count} sản phẩm cho "{query}"',
  noResultsFor: 'Không tìm thấy kết quả cho "{query}"', noFavorites: 'Chưa có sản phẩm yêu thích', favoriteHint: 'Bấm tim trên sản phẩm để thêm vào danh sách',
  noResults: 'Không tìm thấy kết quả', searchHint: 'Thử từ khóa khác hoặc duyệt danh mục', noProducts: 'Chưa có sản phẩm',
  sales: '{count} bán', views: '{count} lượt xem', description: 'Mô tả', price: 'Giá', downloadFree: 'Tải miễn phí',
  favorite: 'Yêu thích', liked: 'Đã thích', copyLink: 'Copy link', copied: 'Đã copy', report: 'Báo cáo', addToCart: 'Thêm vào giỏ', buyNow: 'Mua ngay', downloading: 'Đang tải...', comingSoon: 'Sắp mở bán',
  cartEmpty: 'Giỏ hàng trống', continueShopping: 'Tiếp tục mua sắm', total: 'Tổng cộng', getFree: 'Nhận sản phẩm miễn phí',
  paymentLocked: 'Thanh toán đang tạm khóa', clearAll: 'Xóa tất cả', marketplaceAbout: 'Marketplace plugin, script và extension dành cho REAPER. Chất lượng cao, giá hợp lý.',
  marketplace: 'Marketplace', allProducts: 'Tất cả sản phẩm', support: 'Hỗ trợ', installGuide: 'Hướng dẫn cài đặt', contact: 'Liên hệ',
  refundPolicy: 'Chính sách hoàn tiền', forSellers: 'Dành cho Seller', sellProduct: 'Đăng bán sản phẩm', developerGuide: 'Hướng dẫn phát triển', rights: 'Đã đăng ký bản quyền.',
  forReaper: 'cho REAPER', removeFromWishlist: 'Bỏ {title} khỏi yêu thích', addToWishlist: 'Thêm {title} vào yêu thích', ratingOutOfFive: '{rating} trên 5 sao', productTags: 'Thẻ sản phẩm', downloadPurchased: 'Tải xuống (đã mua)',
  sellerDashboard: 'Bảng điều khiển người bán', apiDocs: 'Tài liệu API',
}

const translations: Record<Exclude<Locale, 'en' | 'vi'>, Messages> = {
  zh: { language:'语言', search:'搜索插件、脚本、教程...', upload:'发布产品', sellerApply:'成为卖家', productsManage:'管理产品', settings:'设置', logout:'退出登录', cart:'购物车', login:'登录', all:'全部', free:'免费', bestSelling:'畅销', featured:'精选', latest:'最新', popular:'最受欢迎', topRated:'评分最高', priceLow:'价格：从低到高', priceHigh:'价格：从高到低', sort:'排序：', categories:'分类', home:'首页', searchShort:'搜索', wishlist:'收藏', notifications:'通知', help:'帮助', new:'新品', trending:'热门趋势', recentlyViewed:'最近浏览', clear:'清除', products:'{count} 个产品', productsFor:'“{query}”的 {count} 个产品', noResultsFor:'未找到“{query}”的结果', noFavorites:'暂无收藏产品', favoriteHint:'点击产品上的爱心即可收藏', noResults:'未找到结果', searchHint:'尝试其他关键词或浏览分类', noProducts:'暂无产品', sales:'已售 {count}', views:'{count} 次浏览', description:'描述', price:'价格', downloadFree:'免费下载', favorite:'收藏', liked:'已收藏', copyLink:'复制链接', copied:'已复制', report:'举报', addToCart:'加入购物车', buyNow:'立即购买', downloading:'下载中...', comingSoon:'即将推出', cartEmpty:'购物车为空', continueShopping:'继续购物', total:'总计', getFree:'获取免费产品', paymentLocked:'支付暂时不可用', clearAll:'全部清除', marketplaceAbout:'面向 REAPER 的插件、脚本和扩展市场。优质且价格合理。', marketplace:'市场', allProducts:'所有产品', support:'支持', installGuide:'安装指南', contact:'联系我们', refundPolicy:'退款政策', forSellers:'卖家专区', sellProduct:'发布产品', developerGuide:'开发指南', rights:'版权所有。', forReaper:'适用 REAPER', removeFromWishlist:'从收藏夹中移除 {title}', addToWishlist:'将 {title} 添加到收藏夹', ratingOutOfFive:'{rating} / 5 星', productTags:'产品标签', downloadPurchased:'下载（已购买）', sellerDashboard:'卖家后台', apiDocs:'API 文档' },
  ja: { language:'言語', search:'プラグイン、スクリプト、チュートリアルを検索...', upload:'商品を出品', sellerApply:'販売者になる', productsManage:'商品管理', settings:'設定', logout:'ログアウト', cart:'カート', login:'ログイン', all:'すべて', free:'無料', bestSelling:'ベストセラー', featured:'注目', latest:'最新', popular:'人気順', topRated:'高評価', priceLow:'価格：安い順', priceHigh:'価格：高い順', sort:'並び替え：', categories:'カテゴリー', home:'ホーム', searchShort:'検索', wishlist:'お気に入り', notifications:'通知', help:'ヘルプ', new:'新着', trending:'トレンド', recentlyViewed:'最近見た商品', clear:'クリア', products:'{count} 商品', productsFor:'「{query}」の検索結果 {count} 件', noResultsFor:'「{query}」の結果が見つかりません', noFavorites:'お気に入りはまだありません', favoriteHint:'ハートを押して商品を保存', noResults:'結果が見つかりません', searchHint:'別のキーワードまたはカテゴリーをお試しください', noProducts:'商品はまだありません', sales:'{count} 件販売', views:'{count} 回表示', description:'説明', price:'価格', downloadFree:'無料ダウンロード', favorite:'お気に入り', liked:'お気に入り済み', copyLink:'リンクをコピー', copied:'コピー済み', report:'報告', addToCart:'カートに追加', buyNow:'今すぐ購入', downloading:'ダウンロード中...', comingSoon:'近日公開', cartEmpty:'カートは空です', continueShopping:'買い物を続ける', total:'合計', getFree:'無料商品を入手', paymentLocked:'決済は一時停止中です', clearAll:'すべて削除', marketplaceAbout:'REAPER向けプラグイン、スクリプト、拡張機能のマーケットプレイス。', marketplace:'マーケット', allProducts:'すべての商品', support:'サポート', installGuide:'インストールガイド', contact:'お問い合わせ', refundPolicy:'返金ポリシー', forSellers:'販売者向け', sellProduct:'商品を出品', developerGuide:'開発者ガイド', rights:'無断転載を禁じます。', forReaper:'REAPER用', removeFromWishlist:'{title} をお気に入りから削除', addToWishlist:'{title} をお気に入りに追加', ratingOutOfFive:'5つ星中{rating}つ', productTags:'商品タグ', downloadPurchased:'ダウンロード（購入済み）', sellerDashboard:'販売者ダッシュボード', apiDocs:'API ドキュメント' },
  ko: { language:'언어', search:'플러그인, 스크립트, 튜토리얼 검색...', upload:'제품 등록', sellerApply:'판매자 되기', productsManage:'제품 관리', settings:'설정', logout:'로그아웃', cart:'장바구니', login:'로그인', all:'전체', free:'무료', bestSelling:'베스트셀러', featured:'추천', latest:'최신', popular:'인기순', topRated:'평점순', priceLow:'가격 낮은순', priceHigh:'가격 높은순', sort:'정렬:', categories:'카테고리', home:'홈', searchShort:'검색', wishlist:'위시리스트', notifications:'알림', help:'도움말', new:'신규', trending:'인기 급상승', recentlyViewed:'최근 본 상품', clear:'지우기', products:'제품 {count}개', productsFor:'“{query}” 제품 {count}개', noResultsFor:'“{query}” 결과가 없습니다', noFavorites:'찜한 제품이 없습니다', favoriteHint:'하트를 눌러 제품을 저장하세요', noResults:'검색 결과 없음', searchHint:'다른 키워드나 카테고리를 확인하세요', noProducts:'제품이 없습니다', sales:'{count}개 판매', views:'조회 {count}회', description:'설명', price:'가격', downloadFree:'무료 다운로드', favorite:'찜하기', liked:'찜 완료', copyLink:'링크 복사', copied:'복사됨', report:'신고', addToCart:'장바구니 담기', buyNow:'바로 구매', downloading:'다운로드 중...', comingSoon:'출시 예정', cartEmpty:'장바구니가 비어 있습니다', continueShopping:'쇼핑 계속하기', total:'합계', getFree:'무료 제품 받기', paymentLocked:'결제가 일시 중지되었습니다', clearAll:'모두 지우기', marketplaceAbout:'REAPER 플러그인, 스크립트 및 확장 프로그램 마켓플레이스.', marketplace:'마켓플레이스', allProducts:'모든 제품', support:'지원', installGuide:'설치 가이드', contact:'문의', refundPolicy:'환불 정책', forSellers:'판매자', sellProduct:'제품 판매', developerGuide:'개발 가이드', rights:'모든 권리 보유.', forReaper:'REAPER용', removeFromWishlist:'위시리스트에서 {title} 제거', addToWishlist:'위시리스트에 {title} 추가', ratingOutOfFive:'5점 만점에 {rating}점', productTags:'제품 태그', downloadPurchased:'다운로드 (구매함)', sellerDashboard:'판매자 대시보드', apiDocs:'API 문서' },
  es: { language:'Idioma', search:'Buscar plugins, scripts, tutoriales...', upload:'Publicar producto', sellerApply:'Ser vendedor', productsManage:'Gestionar productos', settings:'Ajustes', logout:'Cerrar sesión', cart:'Carrito', login:'Iniciar sesión', all:'Todo', free:'Gratis', bestSelling:'Más vendidos', featured:'Destacados', latest:'Novedades', popular:'Más populares', topRated:'Mejor valorados', priceLow:'Precio: menor a mayor', priceHigh:'Precio: mayor a menor', sort:'Ordenar:', categories:'Categorías', home:'Inicio', searchShort:'Buscar', wishlist:'Favoritos', notifications:'Notificaciones', help:'Ayuda', new:'NUEVO', trending:'Tendencias', recentlyViewed:'Vistos recientemente', clear:'Limpiar', products:'{count} productos', productsFor:'{count} productos para “{query}”', noResultsFor:'Sin resultados para “{query}”', noFavorites:'Aún no hay favoritos', favoriteHint:'Pulsa el corazón para guardar un producto', noResults:'No se encontraron resultados', searchHint:'Prueba otra palabra o categoría', noProducts:'Aún no hay productos', sales:'{count} vendidos', views:'{count} vistas', description:'Descripción', price:'Precio', downloadFree:'Descarga gratis', favorite:'Favorito', liked:'En favoritos', copyLink:'Copiar enlace', copied:'Copiado', report:'Reportar', addToCart:'Añadir al carrito', buyNow:'Comprar ahora', downloading:'Descargando...', comingSoon:'Próximamente', cartEmpty:'El carrito está vacío', continueShopping:'Seguir comprando', total:'Total', getFree:'Obtener productos gratis', paymentLocked:'Pagos temporalmente no disponibles', clearAll:'Vaciar todo', marketplaceAbout:'Marketplace de plugins, scripts y extensiones para REAPER.', marketplace:'Marketplace', allProducts:'Todos los productos', support:'Soporte', installGuide:'Guía de instalación', contact:'Contacto', refundPolicy:'Política de reembolso', forSellers:'Para vendedores', sellProduct:'Vender un producto', developerGuide:'Guía para desarrolladores', rights:'Todos los derechos reservados.', forReaper:'para REAPER', removeFromWishlist:'Eliminar {title} de favoritos', addToWishlist:'Añadir {title} a favoritos', ratingOutOfFive:'{rating} de 5 estrellas', productTags:'Etiquetas del producto', downloadPurchased:'Descargar (Comprado)', sellerDashboard:'Panel de vendedor', apiDocs:'Documentación de la API' },
  fr: { language:'Langue', search:'Rechercher plugins, scripts, tutoriels...', upload:'Publier un produit', sellerApply:'Devenir vendeur', productsManage:'Gérer les produits', settings:'Paramètres', logout:'Déconnexion', cart:'Panier', login:'Connexion', all:'Tout', free:'Gratuit', bestSelling:'Meilleures ventes', featured:'En vedette', latest:'Nouveautés', popular:'Plus populaires', topRated:'Mieux notés', priceLow:'Prix croissant', priceHigh:'Prix décroissant', sort:'Trier :', categories:'Catégories', home:'Accueil', searchShort:'Recherche', wishlist:'Favoris', notifications:'Notifications', help:'Aide', new:'NOUVEAU', trending:'Tendances', recentlyViewed:'Vus récemment', clear:'Effacer', products:'{count} produits', productsFor:'{count} produits pour « {query} »', noResultsFor:'Aucun résultat pour « {query} »', noFavorites:'Aucun favori pour le moment', favoriteHint:'Appuyez sur le cœur pour enregistrer un produit', noResults:'Aucun résultat', searchHint:'Essayez un autre mot-clé ou une catégorie', noProducts:'Aucun produit', sales:'{count} vendus', views:'{count} vues', description:'Description', price:'Prix', downloadFree:'Télécharger gratuitement', favorite:'Favori', liked:'En favoris', copyLink:'Copier le lien', copied:'Copié', report:'Signaler', addToCart:'Ajouter au panier', buyNow:'Acheter', downloading:'Téléchargement...', comingSoon:'Bientôt disponible', cartEmpty:'Votre panier est vide', continueShopping:'Continuer vos achats', total:'Total', getFree:'Obtenir les produits gratuits', paymentLocked:'Paiements temporairement indisponibles', clearAll:'Tout effacer', marketplaceAbout:'Marketplace de plugins, scripts et extensions pour REAPER.', marketplace:'Marketplace', allProducts:'Tous les produits', support:'Assistance', installGuide:'Guide d’installation', contact:'Contact', refundPolicy:'Politique de remboursement', forSellers:'Pour les vendeurs', sellProduct:'Vendre un produit', developerGuide:'Guide développeur', rights:'Tous droits réservés.', forReaper:'pour REAPER', removeFromWishlist:'Retirer {title} des favoris', addToWishlist:'Ajouter {title} aux favoris', ratingOutOfFive:'{rating} sur 5 étoiles', productTags:'Étiquettes du produit', downloadPurchased:'Télécharger (Acheté)', sellerDashboard:'Tableau de bord vendeur', apiDocs:'Documentation API' },
  de: { language:'Sprache', search:'Plugins, Skripte, Tutorials suchen...', upload:'Produkt einstellen', sellerApply:'Verkäufer werden', productsManage:'Produkte verwalten', settings:'Einstellungen', logout:'Abmelden', cart:'Warenkorb', login:'Anmelden', all:'Alle', free:'Kostenlos', bestSelling:'Bestseller', featured:'Empfohlen', latest:'Neueste', popular:'Beliebteste', topRated:'Bestbewertet', priceLow:'Preis aufsteigend', priceHigh:'Preis absteigend', sort:'Sortieren:', categories:'Kategorien', home:'Start', searchShort:'Suche', wishlist:'Merkliste', notifications:'Benachrichtigungen', help:'Hilfe', new:'NEU', trending:'Im Trend', recentlyViewed:'Zuletzt angesehen', clear:'Löschen', products:'{count} Produkte', productsFor:'{count} Produkte für „{query}“', noResultsFor:'Keine Ergebnisse für „{query}“', noFavorites:'Noch keine Favoriten', favoriteHint:'Herz antippen, um ein Produkt zu speichern', noResults:'Keine Ergebnisse', searchHint:'Anderes Stichwort oder Kategorie versuchen', noProducts:'Noch keine Produkte', sales:'{count} verkauft', views:'{count} Aufrufe', description:'Beschreibung', price:'Preis', downloadFree:'Kostenlos herunterladen', favorite:'Favorit', liked:'Favorisiert', copyLink:'Link kopieren', copied:'Kopiert', report:'Melden', addToCart:'In den Warenkorb', buyNow:'Jetzt kaufen', downloading:'Wird heruntergeladen...', comingSoon:'Demnächst verfügbar', cartEmpty:'Der Warenkorb ist leer', continueShopping:'Weiter einkaufen', total:'Gesamt', getFree:'Kostenlose Produkte erhalten', paymentLocked:'Zahlungen vorübergehend nicht verfügbar', clearAll:'Alles löschen', marketplaceAbout:'Marktplatz für REAPER-Plugins, Skripte und Erweiterungen.', marketplace:'Marktplatz', allProducts:'Alle Produkte', support:'Support', installGuide:'Installationsanleitung', contact:'Kontakt', refundPolicy:'Rückerstattung', forSellers:'Für Verkäufer', sellProduct:'Produkt verkaufen', developerGuide:'Entwicklerleitfaden', rights:'Alle Rechte vorbehalten.', forReaper:'für REAPER', removeFromWishlist:'{title} aus der Merkliste entfernen', addToWishlist:'{title} zur Merkliste hinzufügen', ratingOutOfFive:'{rating} von 5 Sternen', productTags:'Produkt-Tags', downloadPurchased:'Herunterladen (Gekauft)', sellerDashboard:'Verkäufer-Dashboard', apiDocs:'API-Dokumentation' },
  pt: { language:'Idioma', search:'Buscar plugins, scripts, tutoriais...', upload:'Publicar produto', sellerApply:'Tornar-se vendedor', productsManage:'Gerenciar produtos', settings:'Configurações', logout:'Sair', cart:'Carrinho', login:'Entrar', all:'Todos', free:'Grátis', bestSelling:'Mais vendidos', featured:'Destaques', latest:'Novidades', popular:'Mais populares', topRated:'Melhor avaliados', priceLow:'Menor preço', priceHigh:'Maior preço', sort:'Ordenar:', categories:'Categorias', home:'Início', searchShort:'Buscar', wishlist:'Favoritos', notifications:'Notificações', help:'Ajuda', new:'NOVO', trending:'Em alta', recentlyViewed:'Vistos recentemente', clear:'Limpar', products:'{count} produtos', productsFor:'{count} produtos para “{query}”', noResultsFor:'Nenhum resultado para “{query}”', noFavorites:'Nenhum favorito ainda', favoriteHint:'Toque no coração para salvar um produto', noResults:'Nenhum resultado', searchHint:'Tente outra palavra ou categoria', noProducts:'Nenhum produto ainda', sales:'{count} vendidos', views:'{count} visualizações', description:'Descrição', price:'Preço', downloadFree:'Baixar grátis', favorite:'Favorito', liked:'Favoritado', copyLink:'Copiar link', copied:'Copiado', report:'Denunciar', addToCart:'Adicionar ao carrinho', buyNow:'Comprar agora', downloading:'Baixando...', comingSoon:'Em breve', cartEmpty:'Seu carrinho está vazio', continueShopping:'Continuar comprando', total:'Total', getFree:'Obter produtos grátis', paymentLocked:'Pagamentos temporariamente indisponíveis', clearAll:'Limpar tudo', marketplaceAbout:'Marketplace de plugins, scripts e extensões para REAPER.', marketplace:'Marketplace', allProducts:'Todos os produtos', support:'Suporte', installGuide:'Guia de instalação', contact:'Contato', refundPolicy:'Política de reembolso', forSellers:'Para vendedores', sellProduct:'Vender produto', developerGuide:'Guia do desenvolvedor', rights:'Todos os direitos reservados.', forReaper:'para REAPER', removeFromWishlist:'Remover {title} dos favoritos', addToWishlist:'Adicionar {title} aos favoritos', ratingOutOfFive:'{rating} de 5 estrelas', productTags:'Tags do produto', downloadPurchased:'Baixar (Comprado)', sellerDashboard:'Painel do vendedor', apiDocs:'Documentação da API' },
  th: { language:'ภาษา', search:'ค้นหาปลั๊กอิน สคริปต์ บทเรียน...', upload:'ลงขายสินค้า', sellerApply:'เป็นผู้ขาย', productsManage:'จัดการสินค้า', settings:'การตั้งค่า', logout:'ออกจากระบบ', cart:'ตะกร้า', login:'เข้าสู่ระบบ', all:'ทั้งหมด', free:'ฟรี', bestSelling:'ขายดี', featured:'แนะนำ', latest:'ล่าสุด', popular:'ยอดนิยม', topRated:'คะแนนสูงสุด', priceLow:'ราคาต่ำไปสูง', priceHigh:'ราคาสูงไปต่ำ', sort:'เรียงตาม:', categories:'หมวดหมู่', home:'หน้าแรก', searchShort:'ค้นหา', wishlist:'รายการโปรด', notifications:'การแจ้งเตือน', help:'ช่วยเหลือ', new:'ใหม่', trending:'กำลังมาแรง', recentlyViewed:'ดูล่าสุด', clear:'ล้าง', products:'สินค้า {count} รายการ', productsFor:'สินค้า {count} รายการสำหรับ “{query}”', noResultsFor:'ไม่พบผลลัพธ์สำหรับ “{query}”', noFavorites:'ยังไม่มีสินค้าโปรด', favoriteHint:'แตะหัวใจเพื่อบันทึกสินค้า', noResults:'ไม่พบผลลัพธ์', searchHint:'ลองคำค้นหรือหมวดหมู่อื่น', noProducts:'ยังไม่มีสินค้า', sales:'ขายแล้ว {count}', views:'ดู {count} ครั้ง', description:'รายละเอียด', price:'ราคา', downloadFree:'ดาวน์โหลดฟรี', favorite:'รายการโปรด', liked:'ถูกใจแล้ว', copyLink:'คัดลอกลิงก์', copied:'คัดลอกแล้ว', report:'รายงาน', addToCart:'เพิ่มลงตะกร้า', buyNow:'ซื้อเลย', downloading:'กำลังดาวน์โหลด...', comingSoon:'เร็วๆ นี้', cartEmpty:'ตะกร้าว่าง', continueShopping:'เลือกซื้อต่อ', total:'รวม', getFree:'รับสินค้าฟรี', paymentLocked:'ระบบชำระเงินปิดชั่วคราว', clearAll:'ล้างทั้งหมด', marketplaceAbout:'มาร์เก็ตเพลสปลั๊กอิน สคริปต์ และส่วนขยายสำหรับ REAPER', marketplace:'มาร์เก็ตเพลส', allProducts:'สินค้าทั้งหมด', support:'ช่วยเหลือ', installGuide:'คู่มือติดตั้ง', contact:'ติดต่อ', refundPolicy:'นโยบายคืนเงิน', forSellers:'สำหรับผู้ขาย', sellProduct:'ขายสินค้า', developerGuide:'คู่มือนักพัฒนา', rights:'สงวนลิขสิทธิ์', forReaper:'สำหรับ REAPER', removeFromWishlist:'ลบ {title} ออกจากรายการโปรด', addToWishlist:'เพิ่ม {title} ลงในรายการโปรด', ratingOutOfFive:'{rating} จาก 5 ดาว', productTags:'แท็กสินค้า', downloadPurchased:'ดาวน์โหลด (ซื้อแล้ว)', sellerDashboard:'แดชบอร์ดผู้ขาย', apiDocs:'เอกสาร API' },
  ru: { language:'Язык', search:'Поиск плагинов, скриптов и руководств...', upload:'Опубликовать товар', sellerApply:'Стать продавцом', productsManage:'Управление товарами', settings:'Настройки', logout:'Выйти', cart:'Корзина', login:'Войти', all:'Все', free:'Бесплатно', bestSelling:'Хиты продаж', featured:'Рекомендуемое', latest:'Новинки', popular:'Самые популярные', topRated:'Лучшие оценки', priceLow:'Цена: по возрастанию', priceHigh:'Цена: по убыванию', sort:'Сортировка:', categories:'Категории', home:'Главная', searchShort:'Поиск', wishlist:'Избранное', notifications:'Уведомления', help:'Помощь', new:'НОВИНКА', trending:'В тренде', recentlyViewed:'Недавно просмотренные', clear:'Очистить', products:'Товаров: {count}', productsFor:'Товаров по запросу «{query}»: {count}', noResultsFor:'По запросу «{query}» ничего не найдено', noFavorites:'В избранном пока ничего нет', favoriteHint:'Нажмите на сердце, чтобы сохранить товар', noResults:'Ничего не найдено', searchHint:'Попробуйте другой запрос или категорию', noProducts:'Товаров пока нет', sales:'Продано: {count}', views:'Просмотров: {count}', description:'Описание', price:'Цена', downloadFree:'Скачать бесплатно', favorite:'В избранное', liked:'В избранном', copyLink:'Копировать ссылку', copied:'Скопировано', report:'Пожаловаться', addToCart:'Добавить в корзину', buyNow:'Купить сейчас', downloading:'Загрузка...', comingSoon:'Скоро в продаже', cartEmpty:'Корзина пуста', continueShopping:'Продолжить покупки', total:'Итого', getFree:'Получить бесплатные товары', paymentLocked:'Оплата временно недоступна', clearAll:'Очистить всё', marketplaceAbout:'Маркетплейс плагинов, скриптов и расширений для REAPER. Высокое качество по разумной цене.', marketplace:'Маркетплейс', allProducts:'Все товары', support:'Поддержка', installGuide:'Руководство по установке', contact:'Контакты', refundPolicy:'Политика возврата', forSellers:'Для продавцов', sellProduct:'Продать товар', developerGuide:'Руководство разработчика', rights:'Все права защищены.', forReaper:'для REAPER', removeFromWishlist:'Удалить {title} из избранного', addToWishlist:'Добавить {title} в избранное', ratingOutOfFive:'{rating} из 5 звёзд', productTags:'Теги товара', downloadPurchased:'Скачать (Куплено)', sellerDashboard:'Кабинет продавца', apiDocs:'Документация API' },
}

export const messages: Record<Locale, Messages> = { en, vi, ...translations }
